Models/ErrorViewModel.cs
namespace NotDefteri1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Note.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace NotDefteri1.Models
{
    public class Note
    {
        public int Id { get; set; }
        public string noteTitle { get; set; }
        public string noteDescription { get; set; }
        public DateTime noteDate { get; set; }
        public Note()
        {
            this.noteDate = DateTime.UtcNow;
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NotDefteri1.Models;
using System.Diagnostics;

namespace NotDefteri1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NotDefteri1.Data;
using NotDefteri1.Models;

namespace NotDefteri1.Controllers
{
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NotesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Notes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Note.ToListAsync());
        }

        // GET: Notes/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        
        // PoST: Notes/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.Note.Where( j => j.noteTitle.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // GET: Notes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,noteTitle,noteDescription,noteDate")] Note note)
        {
            if (ModelState.IsValid)
            {
                _context.Add(note);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note.FindAsync(id);
            if (note == null)
            {
                return NotFound();
            }
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,noteTitle,noteDescription,noteDate")] Note note)
        {
            if (id != note.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(note.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var note = await _context.Note.FindAsync(id);
            if (note != null)
            {
                _context.Note.Remove(note);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NoteExists(int id)
        {
            return _context.Note.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">MERHABA</h1>
    <p>Not Defteri 1'e hoşgeldiniz.</p>
</div>

Views/Notes/Create.cshtml
@model NotDefteri1.Models.Note

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="noteTitle" class="control-label"></label>
                <input asp-for="noteTitle" class="form-control" />
                <span asp-validation-for="noteTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="noteDescription" class="control-label"></label>
                <input asp-for="noteDescription" class="form-control" />
                <span asp-validation-for="noteDescription" class="text-danger"></span>
            </div>
            <!-- Hidden field for noteDate -->
            <input type="hidden" asp-for="noteDate" value="@DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ")" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Notes/Delete.cshtml
@model NotDefteri1.Models.Note

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.noteTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.noteTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.noteDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.noteDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.noteDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.noteDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Notes/Details.cshtml
@model NotDefteri1.Models.Note

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Note</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.noteTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.noteTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.noteDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.noteDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.noteDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.noteDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Notes/Edit.cshtml
@model NotDefteri1.Models.Note

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="noteTitle" class="control-label"></label>
                <input asp-for="noteTitle" class="form-control" />
                <span asp-validation-for="noteTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="noteDescription" class="control-label"></label>
                <input asp-for="noteDescription" class="form-control" />
                <span asp-validation-for="noteDescription" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Notes/Index.cshtml
@model IEnumerable<NotDefteri1.Models.Note>

@{
    ViewData["Title"] = "Index";
}

<h1>Yeni Oluştur</h1>

<p>
    <a asp-action="Create">Yeni Oluştur</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.noteTitle)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.noteDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.noteTitle)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.noteDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Düzenle</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Ayrıntılar</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Sil</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Notes/ShowSearchForm.cshtml
<h4>Not Ara</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Ara" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NotDefteri1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NotDefteri1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NotDefteri1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notes" asp-action="Index">Notlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notes" asp-action="ShowSearchForm">Arama</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Gizlilik</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NotDefteri1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>